---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: my-password
  namespace: default
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "password"
  namespace: default
spec:
  refreshInterval: "0m"
  target:
    name: password-secret
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "my-password"